Add configure script option "--static" to create statically linked binary executable

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,49 +3,74 @@
 # This script is here for compatibility & may be removed in the future.
 
 TYPE="b"
+STATIC=0
 
 function usage {
-    echo -e "\n    USAGE: ./configure [ option ]"
-    echo -e "\n    Options:\n\t--type=TYPE\tSet to b (default) for binary executable"
-    echo -e "\t\t\ts for Python script\n"
-    echo -e "\t--help\t\tShow this help text\n\n"
+    echo -e "\n    USAGE: ./configure [--help] [--type=TYPE] [--static]"
+	echo -e "\n    Options:"
+	echo -e "\t--help\t\tShow this help text"
+    echo -e "\n\t--type=TYPE\tSet to \"b\" (default) for binary executable"
+    echo -e "\t\t\t\"s\" for Python script"
+    echo -e "\n\t--static\tCreate statically linked executable (binary"
+	echo -e "\t\t\tonly)\n\n"
 }
 
-if [ "${#}" -gt "1" ]
+MAX_ARGS=2
+
+if [ "${#}" -gt "${MAX_ARGS}" ]
 then
     usage
     exit 1
-elif [ "${1}" == "--help" ]
-then
-    usage
-    exit 0
 fi
 
-ARG=($(echo ${1} | tr  "=" " "))
-if [ "${ARG[0]}" == "--type" ]
-then
-    if [ "${ARG[1]}" == "b" ]
-    then
-        TYPE="${ARG[1]}"
-    elif [ "${ARG[1]}" == "s" ]
-    then
-        TYPE="${ARG[1]}"
-    else
-        echo -e "\nBad argument for option \"${ARG[0]}\"\n"
-        exit 1
-    fi
-elif [ "${1}" != "" ]
-then
-    echo -e "\nBad option \"${ARG[0]}\"\n"
-    exit 1
+for A in $@; do
+	if [[ "${A}" == *"="* ]]; then
+		K=($(echo ${A} | tr  "=" " "))
+		if [ "${K[0]}" != "--type" ]; then
+			echo -e "\nERROR: Unknown argument: \"${K[0]}\""
+			exit 1
+		else
+			if [[ "${K[1]}" == "b" || "${K[1]}" == "s" ]]; then
+				TYPE="${K[1]}"
+			else
+				echo -e "\nERROR: Bad argument for option \"${K[0]}\"\n"
+				exit 1
+			fi
+		fi
+	else
+		if [ "${A}" == "--help" ]; then
+			usage
+			exit 0
+		elif [ "${A}" == "--type" ]; then
+			echo -e "\nERROR: Argument ${A} requires a value: ${A}=TYPE"
+			exit 1
+		elif [ "${A}" == "--static" ]; then
+			STATIC=1
+		else
+			echo -e "\nERROR: Unknown argument \"${A}\""
+			exit 1
+		fi
+	fi
+done
+
+if [[ "${TYPE}" == "s" && "${STATIC}" -ne "0" ]]; then
+	echo -e "\nERROR: --static can only be specified with type \"b\""
+	exit 1
 fi
 
+
+# create Makefile
 if [ "${TYPE}" == "b" ]
 then
-    MAKE="bin2header: man src/bin2header.cpp\n\tg++ -O2 -s src/bin2header.cpp -o bin2header"
+	if [ "${STATIC}" -gt "0" ]
+	then
+		MAKE="bin2header: man src/bin2header.cpp\n\tg++ -static -O2 -s src/bin2header.cpp -o bin2header"
+	else
+		MAKE="bin2header: man src/bin2header.cpp\n\tg++ -O2 -s src/bin2header.cpp -o bin2header"
+	fi
 elif [ "${TYPE}" == "s" ]
 then
-    MAKE="bin2header: man src/bin2header.py\n\t@cp -v src/bin2header.py bin2header"
+	MAKE="bin2header: man src/bin2header.py\n\t@cp -v src/bin2header.py bin2header"
 fi
 
 # Install file
@@ -65,4 +90,3 @@ echo -e "\nDone!"
 echo -e "\nNow run \"make\" and \"make install\"\n"
 
 exit 0
-    
